- src/lib/adapters/firebase/index.ts
- src/lib/adapters/firebase/schemas.ts
- src/lib/adapters/index.ts
- src/lib/adapters/waku/index.ts
- src/lib/objects/hello-world/hello-world-receiver.svelte
- src/lib/objects/hello-world/hello-world-sender.svelte
- src/lib/objects/hello-world/hello-world.svelte
- src/lib/objects/hello-world/index.ts
- src/lib/objects/index.d.ts
- src/lib/objects/lookup.ts
- src/lib/objects/waku-object.svelte
- src/lib/stores/objects.ts
This PR adds the functionality to update the object store in a generic way when an external event happens. Currently it's only updated when there is a data message coming in, but later more events (e.g. transactions) can be added.
The idea is that each object defines a `WakuObjectDescriptor` which may define functionality what should happen when an external event happens (e.g. `onMessage`). I realized that in order to keep the data flow uni-directional the update needs to happen through the adapter and that will update the store. I attached a small diagram about this (which require more work I admit :smile:  ).
Known issues: 
- the firebase update checks the `timestamp` of a message to see if it has been applied for the store already. However this may introduce inconsistencies. For …
> feat: waku object updateStore

- src/lib/adapters/firebase/index.ts
- src/lib/adapters/waku/index.ts
- src/lib/objects/hello-world/index.ts
- src/lib/objects/index.d.ts
This PR addresses one of the issues from #105, that there was no way in the `onMessage` to differentiate if a message originated locally or remotely. By adding an `address` field that contains the address of the user it is possible to compare this value to the recipient of the message.
> feat: add address to onMessage

- src/lib/objects/index.d.ts
- src/lib/objects/send_transaction/chat.svelte
- src/lib/objects/send_transaction/standalone.svelte
- src/lib/stores/chat.ts
It bothered me that there were a lot of `unknown`s on the waku interfaces, sometimes even multiple different objects were `unknown`. This is an attempt to improve the situation.
> feat: improve typing by eliminating unknown types

- src/lib/objects/payggy/standalone.svelte
- Close button on Payggy object header now goes back to chat screen.
- Add autofocus to amount field
> chore: fix action on Close button

- src/index.test.ts
- src/lib/components/asset.svelte
- src/lib/objects/payggy/chat.svelte
- src/lib/objects/payggy/standalone.svelte
- src/lib/utils/format.test.ts
- src/lib/utils/format.ts
Resolves #169 
This add token manipulation methods which have full bigint precision
Method `toBigInt` - validates and parses string representing token into bigint representation
✓ with value=1.234567890123456789 and decimals=18 should return 1234567890123456789
✓ with value=1.234567890123456789 and decimals=6 should return 1234567
✓ with value=0.00012345 and decimals=3 should return 0
✓ with value=0.0009999 and decimals=3 should return 0
✓ with value=0.001 and decimals=3 should return 1
✓ with value=0 and decimals=3 should return 0
✓ with value=0.0 and decimals=3 should return 0
✓ with value=1 and decimals=3 should return 1000
Method `toSignificant` - formats token representation with amount as bigint and decimals to string which has some minimal fractional significant digits
✓ with …
> feat: to significant digits token amount formatting

- knip.ts
- package.json
- pnpm-lock.yaml
- src/lib/adapters/firebase/index.ts
- src/lib/adapters/firebase/schemas.ts
- src/lib/adapters/index.ts
- src/lib/adapters/transaction.ts
- src/lib/adapters/waku/index.ts
- src/lib/objects/adapter.ts
- src/lib/objects/chat.svelte
- src/lib/objects/hello-world/index.ts
- src/lib/objects/index.d.ts
- src/lib/objects/payggy/chat.svelte
- src/lib/objects/payggy/index.ts
- src/lib/objects/payggy/schemas.ts
- src/lib/objects/payggy/standalone.svelte
- src/lib/objects/ui.svelte
- src/lib/utils/error.ts
- src/lib/utils/schemas.ts
- src/routes/dev/+page.svelte
- src/routes/identity/+page.svelte
- src/routes/identity/account/+page.svelte
- src/routes/identity/new/+page.svelte
- src/routes/invite/[address]/+page.svelte
MVP for blockchain transactions. Automatically updates the balance when a transaction was sent/received.
It is already quite big, so it would be good to merge. There are known issues, planned to be fixed in later PRs:
Other observations
> feat: blockchain transactions

- src/lib/components/chat-message.svelte
Known issue: This won't work on Firefox. 
CSS doesn't have a "previous" sibling selector, so I had to use the :has() relational pseudo-class to achieve the same result. Unfortunately, :has() is not yet supported on Firefox (see [here](https://caniuse.com/?search=%3Ahas)). 
The alternative solution would be to use javascript to achieve the desired result, however I believe that since this is a visual enhancement, the performance cost might not be worth it.
> style: fix corners and spacing on chat bubbles

- package.json
- pnpm-lock.yaml
- src/lib/adapters/balance.ts
- src/lib/adapters/firebase/index.ts
- src/lib/adapters/firebase/schemas.ts
- src/lib/adapters/index.ts
- src/lib/adapters/transaction.ts
- src/lib/adapters/waku/index.ts
- src/lib/components/asset.svelte
- src/lib/objects/adapter.ts
- src/lib/objects/chat.svelte
- src/lib/objects/hello-world/index.ts
- src/lib/objects/index.d.ts
- src/lib/objects/payggy/chat.svelte
- src/lib/objects/payggy/index.ts
- src/lib/objects/payggy/schemas.ts
- src/lib/objects/payggy/standalone.svelte
- src/lib/objects/schemas.ts
- src/lib/objects/ui.svelte
- src/lib/utils/format.ts
- src/routes/chat/[id]/object/new/+page.svelte
- src/routes/dev/+page.svelte
- src/routes/identity/account/+page.svelte
With this PR the Payggy object is able to set the status of the transactions on the backend correctly and update it with messages. It only sends the transaction hash in the messages and the peer in the chat reads the transaction from the blockchain based on that.
What is done:
- this was done in order to avoid possible race conditions 
- instead there is a new `updateStore` function passed as argument
Known issues:
- One example: https://github.com/logos-innovation-lab/waku-objects-playground/issues/182
> feat: transaction status

- src/lib/adapters/waku/index.ts
- src/lib/objects/payggy/index.ts
- src/lib/objects/payggy/standalone.svelte
This is a fix for avoiding two widgets in the chat when sending a transaction. It works by waiting for the transaction state change when the message arrives and updating the object's store when that happens.
An edge case where this would not work is when the app is reloaded when the transaction is in pending state. If that happens the transaction will forever stay in pending state. A solution to fix this would be some kind of internal queue for pending transactions.
Fixes #187
> fix: transaction status update

- package.json
- pnpm-lock.yaml
- src/cli/cli.ts
For the testing of the group chat I will need some tooling to be able to create scenarios automatically. I already had a CLI tool for funding a node and checking balances, it makes sense to add more commands there.
Usage:
`pnpm cli fund <address> [amount=1] [fee=0.1]`
`pnpm cli balance <address>`
`pnpm cli txinfo <hash>`
> feat: cli with fund, balance and txinfo commands

- src/lib/components/chat-message.svelte
- src/lib/components/object-bubble.svelte
- src/lib/objects/payggy/chat.svelte
Payggy bubble is now always fullwidth.
I added a `fullwidth` prop to the ChatMessage component so we can specify per waku object.
Solves #214
> style: make Payggy bubble fullwidth

- src/cli/cli.ts
- src/lib/adapters/index.ts
- src/lib/adapters/transaction.ts
- src/lib/adapters/waku/index.ts
- src/lib/objects/adapter.ts
- src/lib/objects/schemas.ts
- src/routes/chat/[id]/+page.svelte
Things to do (likely in separate PR):
> feat: erc20 transactions in paygy

- src/lib/adapters/index.ts
- src/lib/adapters/waku/index.ts
- src/routes/invite/[address]/+page.svelte
Resolves #186 but likely needs some styling love.
Please note, that the design in sketch is quite different, because it has a specific version of connect identity screen. I would suggest that we do not implement it at least now (and I see it as quite low priority). See attached screenshots.
How the invite screen looks as of this PR:
Designs in sketch:
> feat: show name and avatar on invite screen

- src/routes/group/chat/[id]/+page.svelte
There is currently only one action implemented for the group chat - group settings. This PR replaces the previously used Edit icon with the group icon shown on the design
> style: replace group settings icon

- src/lib/adapters/index.ts
- src/lib/adapters/waku/index.ts
- src/lib/adapters/waku/types.ts
- src/lib/adapters/waku/waku.ts
- src/lib/adapters/waku/wakustore.ts
- src/lib/stores/chat.ts
- src/routes/+page.svelte
- src/routes/chat/[id]/+page.svelte
- src/routes/group/chat/[id]/+page.svelte
- src/routes/group/chat/[id]/edit/+page.svelte
- src/routes/invite/[address]/+page.svelte
This is quite a major change to address many previous issues regarding reliability and consistency. Introduces a `Wakustore` type that is loosely modeled after the `Firestore` API from Firebase. There are also new types introduced to differentiate between what is stored on the waku network and what is the local svelte store.
- There is proper history management for the private and group messages and it is based on the implementation of status-web that uses the `timestamp` of the waku messages and time based queries. (Fixes #294 and #309) Previously the `Message` type also defined a timestamp, but that is set by the sender and not the node, so it is not suitable for querying. Because of this there is a hack to overwrite the `Message` timestamp with the waku message's timestamp.
- Added …
> refactor: waku storage

- src/lib/adapters/index.ts
- src/lib/adapters/waku/index.ts
- src/lib/adapters/waku/types.ts
- src/lib/objects/chat.svelte
- src/lib/objects/hello-world/hello-world-receiver.svelte
- src/lib/objects/hello-world/hello-world.svelte
- src/lib/objects/index.d.ts
- src/lib/objects/ui.svelte
- src/lib/stores/chat.ts
- src/lib/stores/objects.ts
- src/routes/chat/[id]/object/new/+page.svelte
The main goal here was to eliminate the `unknown` types from the Waku Object interface. The solution was to introduce a new type called `JSONSerializable` because essentially we need to serialize these objects to JSON in order to store and transmit. Therefore this can help eliminating the usage of types which cannot be serialized to JSON (e.g. `Date`, functions, etc.) at the type system level.
> refactor: better type safety for waku object types

- src/lib/objects/index.d.ts
There was a bug in the type definition of `JSONSerializable` type that was not caught by the review, neither by the Typescript compiler :grin: . The `JSONValue` was the original name of the `JSONSerializable` but after renaming I forgot to update all occurrences.
After fixing that there was a compiler error of using `{ [key: string]: JSONSerializable }` so I replaced it with a `Record` type instead.
> fix: JSONSerializable type

- src/lib/adapters/waku/index.ts
- src/lib/objects/chat.svelte
- src/lib/objects/index.d.ts
- src/lib/objects/ui.svelte
There is a regression caused by the type-safety refactor and it makes Payggy (and any other WO) using the object store to fail. 
This is just a temporary fix to make it work again, however this is still not typesafe and not completely correct, because `store` can be `undefined`, but it is not a valid `JSONSerializable` value. Still it works for now and in a later PR it can be fixed properly.
> fix: undefined store

- src/routes/+page.svelte
- src/routes/chat/[id]/+page.svelte
- src/routes/group/chat/[id]/+page.svelte
Currently it is possible to receive messages where the text is undefined (the current bot version sometimes sends like that). 
The nice solution would be to validate incoming messages. In the meanwhile this is a workaround to make the page load if that happens.
> fix: more robust message handling

- src/routes/+page.svelte
The chat bots use HTML entities for special characters and they were not correctly displayed in the chat list. This PR fixes that.
> fix: html entities in chat list

- src/lib/adapters/waku/waku.ts
This logs `lighPush.send` errors to debug issues related to disconnections. We should probably throw this error at some point and handle it in the UI.
> chore: log lightpush issues

- knip.ts
- package.json
- pnpm-lock.yaml
- src/lib/objects/chat.svelte
- src/lib/objects/external/chat.svelte
- src/lib/objects/external/dispatch.ts
- src/lib/objects/external/iframe.svelte
- src/lib/objects/external/index.ts
- src/lib/objects/external/lib.ts
- src/lib/objects/external/standalone.svelte
- src/lib/objects/external/template.html
- src/lib/objects/index.d.ts
- src/lib/objects/payggy/standalone.svelte
- src/routes/chat/[id]/object/new/+page.svelte
This is the host side of this [PR](https://github.com/logos-innovation-lab/waku-objects/pull/21). First that PR needs to be reviewed, merged and published to npmjs so that this one can use it as a dependency. Until that this will be broken.
- Added support for reactive `args`, so that when they change in the host application (e.g. when there is a new user added to a group chat) then a message is sent to the external object to update the arguments and possibly re-render. There is some optimization so that the hash of the serialized `args` is stored on the host side, and an update is only sent if that changes.
- There is also a new message called `init` that the object sends to the host app when the object initialization is complete, so that the host app can send the updated `args` (which …
> feat: external object props

- package.json
- pnpm-lock.yaml
- src/cli/cli.ts
The CLI was broken, because it imported files that imported paths that was defined in the `tsconfig.json` and `ts-node` did not support that. This PR replaces `ts-node` with `tsx` that supports tsconfig paths.
Also there are new commands for testing chat related functionality:
- `pnpm cli waku profile <address>`: prints the profile belonging to an address
- `pnpm cli waku group-chat <address>`: prints the group chats
- `pnpm cli waku chats <address>`: prints the chats object
- `pnpm cli waku private-message <address>`: prints the private messages
- `pnpm cli waku objects <address>`: prints the object store
- `pnpm cli waku send <from> <to> <message>` sends a private `message` from a user (or group) to another one
- `pnpm cli waku invite <from> <to> <chat-id>` invite a user to a group chat
> feat: cli uses tsx instead of ts-node

- src/lib/adapters/waku/index.ts
- src/lib/adapters/waku/waku.ts
- src/lib/adapters/waku/wakustore.ts
This PR contains multiple improvements that I found during testing with the bots:
- Limit the number of messages in a chat to 100 (can be changed arbitrarily. This is needed because if the chat grows too long then the browser won't be able to load it and will use too much memory. Obviously this comes with old messages to be forgotten, maybe this could be added as an extra feature with a button to load historical messages on a per-demand basis.
- Logs the console with debug loglevel if the waku is connected or not. This gives a nice visual feedback that helps evaluating intuitively the quality of the connection. Currently I see a disconnect in every 30 seconds (see this [issue](https://github.com/waku-org/js-waku/issues/1565) about it)
- Insert the timestamp to subscribed messages too, …
> feat: waku improvements

- src/lib/utils/text.test.ts
- src/lib/utils/text.ts
- src/routes/group/chat/[id]/+page.svelte
- src/routes/styles.css
This PR adds @mentions to group chats. It consists of several parts:
- Replaces the `@name` in the original text to `@address` in the actual text message before sending. This way if the users change their display name the mention will be still relevant.
- It replaces back to `@name` from `@address` before the message is displayed
- Any `@mention` will be replaced by **bold** text before the message is displayed.
> feat: mentions

- src/routes/chat/[id]/+page.svelte
- src/routes/group/chat/[id]/+page.svelte
This removes the add object/image dropdown. Instead, clicking the + button takes you directly to new object. In the last mile document we agreed that instead of uploading pictures we might implement galery waku object.
> feat: remove add images or object dropdown

- src/lib/objects/external/lib.ts
- src/lib/objects/external/template.html
We should also remove the `'self'` in `script-src` for the Waku Objects, as it's no longer necessary.
Ideally, the entry script would be hashed and added to `src-script` with `sha256-*`, like we do for the embeds, but that doesn't seem to work for some reason? The current solution might be a bit too open and allow Waku Objects to import Playground scripts, which might be problematic.
> fix: entry script CSP for Firefox

- src/lib/adapters/waku/index.ts
- src/lib/adapters/waku/safe-waku.ts
- src/lib/adapters/waku/waku.ts
- src/lib/stores/chat.ts
- src/routes/chat/[id]/+page.svelte
- src/routes/group/chat/[id]/+page.svelte
This PR adds a safe wrapper around sending and receiving waku messages. Also moves queueing and retry/resync logic to the safe wrapper from the adapter. The long term goal is to abstract away the connectivity related issues from the application.
Notes:
- There are known issues with `waku-js` (such as [this](https://github.com/waku-org/js-waku/issues/1569), [this](https://github.com/waku-org/js-waku/issues/1562) and [this](https://github.com/waku-org/js-waku/issues/1562)) that makes it very difficult or impossible to handle all errors gracefully in a wrapper at the moment.
- The Svelte `Readable` `subscribe` function calls the callback function immediately, which is not needed, that's why there are the `firstChatStoreSave` and `firstObjectStoreSave` variables.
- This safe wrapper approach …
> feat: safe waku

- src/lib/components/badge.svelte
- src/routes/+page.svelte
Remove leftover debug output from the chat list after #403.
Also added `nowrap` css to badge to avoid a screen filled with broken badges like in the picture. This improves #335 but does not solve it completely.
> fix: remove leftover

- src/lib/adapters/waku/index.ts
The #403 join screen to private chats PR added an extra step to the invite flow when accepting the invite, which is unnecessary. This PR fixes that.
> fix: invite flow

- src/routes/chat/[id]/+page.svelte
- src/routes/invite/[address]/+page.svelte
Currently the invite flow is buggy if you use an invite link from someone else you will be redirected to a random chat.
This PR fixes this, the root cause is that we did not check if the chat store is already loaded when saving the chat ids for later comparison, therefore the original set was empty and then when the chat store loaded it redirected you to a random chat from it.
The PR contains a check if the chat store is loaded and also the background detection should only start if you are the one sharing your link. I also added another fix for the join screen, it incorrectly showed your common groups with a contact because of an incorrect comparison.
> fix: invite redirect bug

- src/lib/components/chat-date-badge.svelte
- src/lib/components/chat-message.svelte
- src/lib/utils/format.ts
- src/routes/chat/[id]/+page.svelte
- src/routes/group/chat/[id]/+page.svelte
Closes #32 
There were several simplifications compared to the original design:
> feat: chat timestamp

- src/lib/adapters/waku/index.ts
resolves #402
Actually not sure if it was not fixed by some other PR anymore, but this works and is computationally more efficient.
> fix: rename group

- src/lib/adapters/waku/safe-waku.ts
I find that 10 times a second is to excessive, it is better to wait one sec before retrying.
> fix: change resubscribe timeout from 100 to 1000

- package.json
- pnpm-lock.yaml
- src/lib/utils/image.ts
Resolves #430 
We have to lazy-load the library as it only works in browser. That's why there is:
```ts
const heic2any = await import('heic2any')
const out = await heic2any.default({
blob: heicFile,
toType: 'image/png',
})
```
> feat: heic image support

- src/lib/adapters/waku/index.ts
This PR fixes an issue when the group changes while you are offline. The fix is to load the state before subscribing to changes.
> fix: load group info when starting the app

- src/lib/adapters/waku/index.ts
Previously it was possible to add the same user to a group multiple times (it was worse without the #457 fix). This PR fixes that and also makes sure that if there is a group already duplicate members it will be loaded correctly and won't show duplicates.
> fix: duplicate users in group

- src/lib/components/badge.svelte
> fix: badge for multiple digits or NEW text

- package.json
- pnpm-lock.yaml
- src/lib/adapters/waku/safe-waku.ts
- src/lib/adapters/waku/waku.ts
Changes in this PR:
- Connect to a cluster using 3 go-waku nodes
- Add `pingKeepAlive` to make connectivity more stable
- Use latest version of `js-waku` and interfaces
- Update the error handling to the latest version
Also closes #375 and closes #373
> fix: waku improvements

- src/lib/adapters/waku/index.ts
Before this change if the user profile was not found then an exception was thrown silently and it was not possible to join to the chat from an invite link. This may happen sometimes when nodes are changed or the data is old and cannot be found on the waku network.
With this PR it is possible to add the user as a contact, although their names will be `undefined`. However as soon as they change their profile and the page is reloaded then the correct profile will be shown.
> feat: make invite more resilient

- src/lib/utils/user.ts
- src/routes/+page.svelte
- src/routes/chat/[id]/+page.svelte
- src/routes/group/chat/[id]/edit/+page.svelte
This PR fixes undefined names in 3 places:
- chat list
- chat view header
- group chat edit page
First I tried to truncate the address with CSS, but it required different solutions in each pages, so eventually just settled on truncating in the `userDisplayName` function.
Before:
After:
> fix: undefined name

- src/lib/adapters/transaction.ts
- src/lib/adapters/waku/index.ts
- src/lib/objects/chat.svelte
- src/lib/objects/external/iframe.svelte
- src/lib/objects/index.d.ts
- src/lib/objects/split/blockchain.ts
- src/lib/objects/split/standalone.svelte
- src/lib/objects/split/views/summary.svelte
- src/lib/objects/ui.svelte
- src/routes/+layout.svelte
Resolves #450
I decided to stor the `chainId` of the different chains into the `BlockchainNetwork` type because:
1. Getting the `chainId` is async call which makes the `args` creation a bit more challenging. Storing it in the `BlockchainNetwork` means we can just get it.
2. This way we can define the chains we want to connect to and then validate with the RPC that we are connected to the right chain. This is done in the main `Layout`.
> feat: extract splitterFactory address to the object and expose chain ID

- src/app.html
- src/lib/stores/is-system-dark.ts
- src/lib/stores/theme.ts
- src/lib/utils/color.ts
- src/routes/+layout.svelte
This should probably be refactored into a:
```html
<svelte:head>
<meta name="theme-color" content={$theme.isDark ? 'black' : 'white'} />
</svelte:head>
```
The issue is that currently there's no easy way to listen to changed about which theme is actually being displayed. If it's the system theme and the system appearance changes, the store does not. The `isSystemDark` variable and listener from #482 should probably be moved to the store?
> feat: sets the right theme color (for iPhones)

- src/lib/adapters/waku/index.ts
Now that the private chats are similar to the group chats in that it requires a single subscription per chat it is easy to add support for multiple devices by not adding the messages directly to the chat but instead adding them when they are received from the subscription.
> feat: multiple device support

- src/cli/cli.ts
- src/lib/adapters/waku/codec.ts
- src/lib/adapters/waku/crypto.test.ts
- src/lib/adapters/waku/crypto.ts
- src/lib/adapters/waku/index.ts
- src/lib/adapters/waku/safe-waku.ts
- src/lib/adapters/waku/waku.ts
- src/lib/adapters/waku/wakustore.ts
- src/routes/group/chat/[id]/edit/+page.svelte
- src/routes/invite/[address]/+page.svelte
**This is a breaking change**
Fixes some of the issues created by this PR: https://github.com/logos-innovation-lab/waku-objects-playground/pull/488
Basically this PR added signing and verification to the data and also changed the code to work with encrypted encoders/decoders as well.
Originally it also contained ECIES encryption but that does not work at the moment in js-waku: https://github.com/waku-org/js-waku/issues/1716
> feat: encryption with signatures

- src/lib/objects/external/iframe.svelte
- src/lib/objects/external/lib.ts
- src/lib/objects/external/standalone.svelte
- src/lib/objects/external/template.html
- src/lib/objects/lookup.ts
- src/routes/identity/+page.svelte
Needs some rebasing and doesn't include the chat flow to add objects. Maybe some additional checks for IPFS should be added as well, but they would be redundant assuming we agree on the `metadata.json` format.
There's a missing piece that is checking the `metadata.json` signature, but that should also be done in the chat flow.
This PR also fixes the CSP security issue where the entrypoint needed to be specified with a URL rather than a hash. The fix was to add the `integrity` prop to the `<script>` tag. I haven't tried this on Firefox though, hopefully this didn't introduce an additional CSP bug.
An example object to be added through the form on the settings tab: `url:https://unpkg.com/@waku-objects/sandbox-example@0.5.0/object`.
> feat: external objects with URL and metadata check

- src/lib/adapters/waku/codec.ts
- src/lib/adapters/waku/crypto.test.ts
- src/lib/adapters/waku/crypto.ts
- src/lib/adapters/waku/index.ts
This PR is based on #495, so that needs to be merged first.
This PR changes the invite to use ECIES instead of a symmetric key so it hides the information for a third-party who sent an invite. So for example if `A` sends an invite to `B` and `C` is already a contact of `B` then previously `C` could see who sent an invite to `B`. After this PR `C` will not know who sent an invite, the only information they can gather is that someone sent an invite. That may be addressed if the invite address is different from the public key and is changed periodically, but that is not part of this PR.
> feat: invite with ECIES

- src/lib/adapters/waku/crypto.ts
- src/lib/adapters/waku/index.ts
- src/routes/group/chat/[id]/edit/+page.svelte
There was an issue that the group chat name and photo was not editable, it always changed back to the original.
This PR fixes that. The root cause of the issue was that when checking the signature we compared the uncompressed public key (which was returned from the signature) with the compressed signature that we store and therefore the check failed.
There is another issue that the `ethers` package uses public keys with `0x` prefix, where the `@noble/crypto` package uses public keys without the `0x` prefix. I added a helper function for comparison (`arePublicKeysEqual`) but unfortunately that only works with direct comparison and therefore less useful when using with arrays (e.g. `includes`).
> fix: group chat editing

- src/lib/adapters/waku/index.ts
- src/routes/babbles/chat/[id]/edit/+page.svelte
Also removed the option for changing the name and avatar from the babbles edit page because it is not working.
> fix: change default babbles name and avatar

- src/routes/babbles/chat/[id]/[[thread_id]]/+page.svelte
Sometimes messages disappear from the waku store. This is a fix for the case if a message's parent is lost to keep at least the rest of the thread.
> fix: babbles messages
