- src/routes/chat/[id]/+page.svelte
> feat: use enter to send message

- src/lib/components/button.svelte
- src/lib/components/icons/arrow-up.svelte
- src/lib/components/icons/chevron-left.svelte
- src/lib/components/textarea.svelte
- src/routes/+page.svelte
- src/routes/chat/[id]/+page.svelte
- src/routes/chat/new/+page.svelte
- src/routes/profile/+page.svelte
- src/routes/request-transaction/+page.svelte
- src/routes/send-transaction/+page.svelte
- src/routes/styles.css
- Edit Button component and update screens that use it
> style: chat screen

- package.json
- pnpm-lock.yaml
- src/lib/adapters/firebase/index.ts
- src/lib/adapters/index.ts
- src/routes/identity/backup/+page.svelte
- src/routes/identity/backup/+page.ts
- src/routes/identity/confirm/+page.svelte
- src/routes/identity/new/+page.ts
> feat: backup identity show mnemonics and copy mechanism

- src/lib/adapters/base/index.ts
- src/routes/identity/+page.svelte
> feat: disconnect identity

- src/routes/chat/[id]/+page.svelte
> feat: autoscroll on sending new message or receiving message

- src/lib/stores/wallet.ts
> refactor: remove unused balances code

- src/lib/components/input-field.svelte
- src/lib/components/textarea.svelte
- src/routes/identity/+page.svelte
- src/routes/identity/account/+page.svelte
- src/routes/identity/backup/+page.svelte
- src/routes/identity/connect/+page.svelte
- src/routes/identity/new/+page.svelte
- src/routes/invite/[address]/+page.svelte
Also adds Input Field component
Issues addressed in this PR
#101
#102
#103
> fix: fix textarea component bugs

- src/routes/+layout.svelte
- src/routes/styles.css
> style: fix page background color

- src/lib/adapters/waku/index.ts
This PR fixes an issue mentioned in #105, that the waku adapter only executed the `onMessage` callback if the message was incoming but not if it was outgoing.
This PR also builds on top of #113 that adds the `address` argument to `onMessage` and therefore makes the distinction possible.
> fix: waku adapter onmessage

- src/routes/+layout.svelte
- src/routes/chat/[id]/+page.svelte
> style: fix empty area below chat input field

- src/lib/adapters/firebase/index.ts
- src/lib/adapters/utils.ts
Might fix the issue mentioned in #115
> fix: contacts not being loaded when chat loads

- src/routes/identity/account/+page.svelte
> feat: make Assets count badge load correct number of assets

- src/lib/components/button-block.svelte
- src/routes/identity/+page.svelte
- Update Account page to use ButtonBlock component
> feat: create ButtonBlock component

- src/lib/components/container.svelte
- src/lib/components/input-field.svelte
- src/routes/+page.svelte
- src/routes/chat/[id]/+page.svelte
- src/routes/chat/[id]/object/new/+page.svelte
- src/routes/identity/+page.svelte
- src/routes/identity/account/+page.svelte
- src/routes/identity/confirm/+page.svelte
- src/routes/identity/new/+page.svelte
- src/routes/invite/[address]/+page.svelte
- Add vertical spacing to Container and update components in use 
- Add label to input component and update components in use
> style: adjust spacings

- src/lib/components/object-link.svelte
- src/routes/chat/[id]/object/new/+page.svelte
- src/routes/styles.css
This PR creates an ObjectLink component, updates its style to match the newest design and applies it to the "Adding WO" screen.
> style: update "Adding WO" screen to newest design

- src/routes/invite/[address]/+page.svelte
TODO: add action to "Renew link" button
> style: add style to Invite page

- src/routes/chat/[id]/+page.svelte
- src/routes/styles.css
> fix: chat scroll on new message and on mount

- src/lib/objects/chat.svelte
- src/lib/objects/hello-world/hello-world.svelte
- src/lib/objects/index.d.ts
- src/lib/objects/send_transaction/chat.svelte
- src/routes/chat/[id]/+page.svelte
> feat: expose chat participants to waku object

- src/lib/components/textarea.svelte
- src/routes/chat/[id]/+page.svelte
> fix: textarea resize on content change

- src/routes/chat/[id]/+page.svelte
> fix: support new lines in messages

- src/lib/components/select.svelte
- src/lib/components/textarea.svelte
Some components were copied from a previous project and contained incorrect variable names. This PR fixes those.
> style: fix var names in components

- src/lib/objects/hello-world/index.ts
- src/lib/objects/index.d.ts
- src/lib/objects/lookup.ts
- src/lib/objects/payggy/index.ts
- src/routes/chat/[id]/object/new/+page.svelte
Added missing fields to the `WakuObjectDescriptor` interface so that the objects can be self-describing and the UI components don't have to know about them.
This also fixes the missing icon problem in the listing.
> feat: use the descriptor for listing objects

- src/lib/components/readonly-text.svelte
- src/routes/identity/backup/+page.svelte
Hopefully solves #167
I don't have Linux so I can't reproduce the reported bug, but the field shouldn't be a `<textarea>` anyway so I replaced it with the ReadonlyText component. Hopefully that solves it.
> chore: replace textarea with ReadonlyText

- src/routes/chat/[id]/+page.svelte
> style: fix chat screen scrollbar

- src/lib/utils/color.ts
- src/routes/+layout.svelte
- src/routes/styles.css
IMHO we can merge this and then tackle the actual dark version of colors in individual components as a separate task PR
> feat: dark mode color switching

- src/routes/identity/+page.svelte
> chore: remove autofocus from Name field

- src/routes/identity/chat/+page.svelte
> chore: fix Chat Appearance screen title

- src/lib/objects/payggy/standalone.svelte
> fix: number conversion exception

- src/routes/styles.css
> style: fix border color on main css file variable

- src/app.html
Added viewport / disable zooming /doubletap zoom
> fix: description and viewport in app.html

- src/routes/invite/[address]/+page.svelte
> fix: invite link takes you to chat if it already exists

- src/app.html
> fix: make manifest path absolute

- src/lib/abis/erc20.json
- src/lib/adapters/balance.ts
- src/lib/adapters/transaction.ts
Resolves #168 
I think the whole fetch balance mechanism should be reviewed. However, not sure if it should be part of this PR.
You can get Chiado GNO token from https://www.gnosisfaucet.com/
> feat: get other ERC20 token balances

- src/routes/+page.svelte
on the first screen, i changed "waku chats" to "Waku Play"
> Change name to Waku Play

- src/lib/stores/theme.ts
> fix: 505 error on identity subpages

- src/routes/+page.svelte
- src/routes/chat/[id]/+page.svelte
> style: fix homepage scrolling

- src/routes/invite/[address]/+page.svelte
> fix: stuck on loading when getting an invite without existing identity

- src/routes/chat/[id]/object/[object_id]/new/[[view]]/+page.svelte
> fix: wrong url in paygy screens

- src/routes/chat/[id]/+page.svelte
> feat: autofocus chat input

- src/lib/components/chat-message.svelte
> style: don't right align messages in chat bubble

- src/lib/adapters/waku/index.ts
Originally was #271, but that got merged accidentally, sorry :smiling_face_with_tear: 
I wanted to merge #265 which was approved, not it is in conflict with main
We either need to revert on main or just apply this fix which fixes #265 for #271.
Temporary fix to make offline group invites work by reading your historical private messages on startup looking for invites to unknown group chats.
Also fixes the profile update function to work with chats with multiple participants.
> fix: offline group invite

- src/lib/adapters/transaction.ts
- src/lib/objects/adapter.ts
- src/lib/objects/chat.svelte
- src/lib/objects/index.d.ts
- src/lib/objects/payggy/chat.svelte
- src/lib/objects/payggy/standalone.svelte
- src/lib/objects/schemas.ts
- src/lib/objects/ui.svelte
- src/lib/routes.ts
- src/lib/utils/format.ts
- src/routes/chat/[id]/object/[object_id]/[instance_id]/[[view]]/+page.svelte
- src/routes/chat/[id]/object/new/+page.svelte
Part of #125
View in chat with icon that can be expanded
Detail view
> feat: details view on waku object

- src/lib/objects/payggy/standalone.svelte
- src/lib/objects/ui.svelte
- src/routes/group/chat/[id]/+page.svelte
- src/routes/group/chat/[id]/edit/+page.svelte
- src/routes/group/new/+page.svelte
> fix: handle chat not being found

- src/lib/components/icons/launch.svelte
- src/lib/components/icons/pending.svelte
- src/lib/components/object-detail-item.svelte
- src/lib/components/readonly-text.svelte
- src/lib/components/timestamp.svelte
- src/lib/objects/payggy/chat.svelte
- src/lib/objects/payggy/standalone.svelte
The ReadonlyText component is a bit buggy but I'd address it in a separate PR since I'll have to updated it globally.
I believe that's also what's causing the animation to be a bit jagged.
> style: Payggy detail screen

- src/lib/adapters/waku/waku.ts
I asked in the waku discord what is the best way to detect if the network connection is lost and this seems be it.
This is the first step towards addressing #282
> feat: onDisconnect callback

- src/lib/components/object-detail-item.svelte
- src/lib/components/readonly-text.svelte
- src/lib/objects/payggy/chat.svelte
- src/lib/objects/payggy/standalone.svelte
- src/routes/+layout.svelte
- src/routes/identity/account/+page.svelte
- src/routes/identity/backup/+page.svelte
- src/routes/invite/[address]/+page.svelte
Updates ReadonlyText component (and pages that use it) and fixes jaggedness of Payggy detail open/close animation
> fix: ReadonlyText component spacings

- src/lib/components/authenticated-only.svelte
- src/lib/components/container.svelte
- src/lib/components/layout.svelte
- src/lib/components/object-detail-item.svelte
- src/lib/components/readonly-text.svelte
- src/lib/components/spacer.svelte
- src/lib/objects/payggy/standalone.svelte
- src/routes/+page.svelte
- src/routes/chat/[id]/+page.svelte
- src/routes/chat/[id]/object/new/+page.svelte
- src/routes/identity/+page.svelte
- src/routes/identity/account/+page.svelte
- src/routes/identity/backup/+page.svelte
- src/routes/identity/chat/+page.svelte
- src/routes/identity/confirm/+page.svelte
- src/routes/identity/connect/+page.svelte
- src/routes/identity/new/+page.svelte
- src/routes/invite/[address]/+page.svelte
Note: This PR doesn't include any changes to the group chat screens - they will be addressed separately, as the styling hasn't been finished for them
Solves #241
> fix: global scrolling issue

- src/lib/objects/payggy/standalone.svelte
> fix: payggy default token balance

- src/routes/identity/chat/+page.svelte
> fix: firefox color picker shape

- src/routes/styles.css
> style: link color

- LICENSE-APACHE-v2
- LICENSE-MIT
- README.md
> feat: license

- src/lib/adapters/waku/index.ts
Added an optimisation to check the existing contacts first when looking up a user. I also changed the names of the functions so that it is more clear what they do.
> refactor: storage user optimisation

- src/routes/+page.svelte
According to the design here: https://www.sketch.com/s/cbdf10a1-c69e-4370-9793-7b89f54452e0/a/WdEmonA
> fix: sender name in chat list

- src/lib/adapters/waku/index.ts
> fix: private chat users

- src/routes/identity/connect/+page.svelte
> fix: trim whitespace and newlines from mnemonic

- src/lib/adapters/index.ts
- src/lib/adapters/waku/index.ts
- src/lib/stores/chat.ts
- src/routes/group/new/+page.svelte
This fixes #339 for group chats. Also made sure that the `updateContactProfiles` function works correctly for group chats.
> fix: group chat users

- src/lib/adapters/balance.ts
- src/lib/adapters/index.ts
- src/lib/adapters/transaction.ts
- src/lib/adapters/waku/index.ts
- src/lib/objects/adapter.ts
- src/lib/objects/external/dispatch.ts
- src/lib/objects/index.d.ts
- src/lib/objects/payggy/standalone.svelte
- src/lib/objects/payggy/views/choose-amount.svelte
- src/lib/objects/payggy/views/confirm-send.svelte
- src/lib/objects/schemas.ts
- src/lib/objects/split/blockchain.ts
- src/lib/objects/split/chat-messages/expense.svelte
- src/lib/objects/split/chat-messages/payment.svelte
- src/lib/objects/split/chat-messages/settle-reminder.svelte
- src/lib/objects/split/chat.svelte
- src/lib/objects/split/components/activity.svelte
- src/lib/objects/split/index.ts
- src/lib/objects/split/schemas.ts
- src/lib/objects/split/standalone.svelte
- src/lib/objects/split/views/accounting.svelte
- src/lib/objects/split/views/activity-history.svelte
- src/lib/objects/split/views/choose-amount.svelte
- src/lib/objects/split/views/collection.svelte
- src/lib/objects/split/views/expense-detail.svelte
- src/lib/objects/split/views/expenses.svelte
- src/lib/objects/split/views/settle-now.svelte
- src/lib/objects/split/views/summary.svelte
- src/lib/objects/ui.svelte
- src/lib/stores/balances.ts
> feat: define split token in one place and use it everywhere in the app

- src/routes/+page.svelte
This PR adds @mention names to the chat list screen too. Also fixes the chat list message view to have text overflow with ellipsis on two lines.
> feat: mentions on chat list screen

- src/lib/objects/split/chat-messages/settle-reminder.svelte
> fix: settle now reminder correctly shows it user owes something.

- src/routes/+page.svelte
- src/routes/chat/[id]/+page.svelte
This PR adds the [join screen](https://www.sketch.com/s/cbdf10a1-c69e-4370-9793-7b89f54452e0/a/Mmxq00b) for private chats, with a `NEW` indicator for chats that are not yet joined. Also sorts the chats in a way that new chats are on the top.
Closes https://github.com/logos-innovation-lab/waku-objects-playground/issues/26
There is a separate known issue with badges: https://github.com/logos-innovation-lab/waku-objects-playground/issues/335
> feat: join screen

- src/lib/utils/format.test.ts
- src/lib/utils/format.ts
- src/routes/+page.svelte
> feat: chat list timestamp

- src/routes/chat/[id]/+page.svelte
- src/routes/invite/[address]/+page.svelte
Depends on #436 to be merged
Fixes #433
> fix: invite button spacing

- src/routes/chat/[id]/+page.svelte
- src/routes/invite/[address]/+page.svelte
> feat: add decline button to invite page

- src/lib/objects/payggy/index.ts
- src/lib/objects/split/index.ts
- src/lib/objects/split/schemas.ts
- src/lib/objects/split/standalone.svelte
- src/lib/objects/split/views/summary.svelte
> fix: split object works after adding new members to chat

- src/routes/+page.svelte
- src/routes/chat/[id]/+page.svelte
> fix: new chats wording

- src/lib/components/chat-message.svelte
- src/routes/+page.svelte
https://github.com/logos-innovation-lab/waku-objects-playground/pull/428#issuecomment-1733248575
> fix: make timestamp sans-serif

- src/lib/objects/payggy/index.ts
> feat: update payggy description

- src/lib/adapters/transaction.ts
> feat: use gnosis chain by default

- src/lib/components/authenticated-only.svelte
- src/lib/components/loading.svelte
- src/lib/objects/payggy/chat.svelte
- src/lib/objects/split/standalone.svelte
- src/lib/objects/split/views/settle-now.svelte
- src/lib/objects/ui.svelte
- src/routes/+page.svelte
- src/routes/group/chat/[id]/edit/+page.svelte
- src/routes/group/new/+page.svelte
- src/routes/identity/account/+page.svelte
- src/routes/invite/[address]/+page.svelte
Partially addresses #360 , I will go through the app and review where we need to have loading state. Also implement it in buttons.
> feat: loading component

- src/lib/adapters/transaction.ts
- src/lib/adapters/waku/waku.ts
Uses 3 new Waku nodes and a new Gnosis RPC endpoint
> feat: demo

- .env
- .gitignore
- README.md
- src/lib/adapters/transaction.ts
- src/lib/adapters/waku/waku.ts
> feat: use env vars to specify chain or waku

- src/routes/group/chat/[id]/+page.svelte
Fixes the first time badge in a group chat.
> fix: group time badge

- src/lib/objects/payggy/views/details.svelte
> fix: replace hardcoded fiat amount

- src/app.html
- src/lib/utils/color.ts
- src/routes/+layout.svelte
This makes it so the theme changes when the system appearance changes from light to dark and vice versa.
> feat: listen for system theme change

- src/routes/group/chat/[id]/edit/+page.svelte
There is a bug that users who are already member of a group show up in the list of users to add.
This PR fixes that.
> fix: group invite member

- src/lib/adapters/waku/safe-waku.ts
- src/lib/adapters/waku/wakustore.ts
Change `queueMessage` to not block (also change the callback type to be async).
> fix: message queue
